NUMPY


A simple list cannot be used to do manipulations so we use Numpy library to do array manipulations

In [5]:
my_list = [1,2,3]

In [6]:
my_list

[1, 2, 3]

Import Numpy and cast the list my_list

In [12]:
import numpy as np

arr= np.array(my_list)

In [13]:
arr

array([1, 2, 3])

To get a 2d array we can use a list of lists

In [14]:
my_lis = [[1,2,3],[4,5,6],[7,8,9]]

In [17]:
arr2 = np.array(my_lis)

In [18]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
# To generate an array automatically

np.arange(0,21)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [21]:
# To generate an array auntomatically within a range and a step size

np.arange(0,21,4)

array([ 0,  4,  8, 12, 16, 20])

In [22]:
# To generate a 1D array with all zeros
# A one dimensional array with have one bracket
np.zeros(3)

array([ 0.,  0.,  0.])

In [24]:
# To generate a 2D array with all zeros--- For this we need to give a ""TUPLE""
# # A 2 dimensional array with have 2 bracket

np.zeros((3,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

LINSPACE will create an equally spaced elements within a given range for a given step size

In linspace the 3rd argument is the number of elements we want whereas in arange it is the step size

In [27]:
np.linspace(0,10,5)

array([  0. ,   2.5,   5. ,   7.5,  10. ])

In [28]:
# Identity Matrix takes a single input and should be a square

np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [29]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [33]:
#To generate random numbers 
# "rand" method produces a random number from 0 to 1 
np.random.rand()

0.3481534142202346

In [34]:
np.random.rand(20)

array([ 0.1715247 ,  0.66976734,  0.53267752,  0.26021934,  0.77373867,
        0.51184947,  0.30303022,  0.39319822,  0.47620469,  0.5229696 ,
        0.84462936,  0.15467239,  0.21758543,  0.66008807,  0.19359802,
        0.15046011,  0.59143293,  0.63631565,  0.42435805,  0.65085956])

In [35]:
np.random.rand(5,5)

array([[ 0.01945534,  0.15439772,  0.25547954,  0.44113306,  0.21157956],
       [ 0.11623229,  0.97022964,  0.17902937,  0.04661248,  0.43249704],
       [ 0.87001918,  0.35079277,  0.530065  ,  0.13056048,  0.75239103],
       [ 0.41192327,  0.27361259,  0.01605462,  0.05190213,  0.71191863],
       [ 0.49903633,  0.65809453,  0.04497622,  0.67187104,  0.06909595]])

In [36]:
# To generate random samples from a normal or gaussian distribution we use random.randn

np.random.randn(4)

array([ 0.15951739,  1.1033668 ,  0.32907509, -1.24175616])

In [37]:
np.random.randn(4,4)

array([[ 0.59385354,  0.32208412,  0.88033762,  0.44939451],
       [-0.68060601,  0.31599015,  0.79660035,  0.04180561],
       [-0.46906224,  1.50042641,  0.72441541, -0.35232091],
       [-0.40449324, -1.91756832, -1.00533974,  0.79570045]])

In [38]:
# To generate a random integer with a range and the number of elements we use random.randint
# Here the lower size is inclusive and the upper size is not included 

np.random.randint(0,100)

34

In [39]:
np.random.randint(0,50,10)

array([22, 26, 46, 29,  5, 46, 35, 16, 19, 34])

RESHAPE METHOD is used to change the shape of the array

In [79]:
arr = np.arange(0,25)

In [80]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [81]:
# The above array arr is a 1D array and if we want to change the shape we can do it using """reshape method"""
# If the array is not filled up i.e  m*n if not equal to total no. of elements we get an error
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [52]:
ranarr = np.random.randint(0,100,20)

In [53]:
ranarr

array([64, 41, 11, 79, 38, 81, 45, 78, 67, 62, 85, 55, 47, 22, 32,  8, 97,
        2, 37, 10])

In [57]:
# To find the max element in the array we use """.MAX() method""" and .min() for the lowest

ranarr.max()

97

In [58]:
# To find the index value of the max value we use """.argmax() method"""

ranarr.argmax()

16

In [82]:
# To find the shape we use """shape""" --- ITS AN ATTRIBUTE NOT A METHOD

arr.shape

(25,)

In [61]:
ranarr.shape

(20,)

In [65]:
# To find the datatype of the array

ranarr.dtype

dtype('int32')

In [67]:
# Another way

from numpy.random import randint
randint(0,5,2)

array([1, 3])

NUMPY INDEXING AND SELECTION

In [93]:
arrs = np.arange(0,10)

In [94]:
arrs

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [95]:
arrs[5]

5

In [96]:
arrs[0:5]

array([0, 1, 2, 3, 4])

In [97]:
arrs[5:]

array([5, 6, 7, 8, 9])

Numpy arrays can be used to broadcast

In [98]:
slice_of_arr = arrs[0:5]

In [100]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [101]:
slice_of_arr[:] = 100

Here all the elements in the slice are replaced. Oringinal array is also replaced because numpy does not store copy of the elements.It replaces everything to avoid space issues

To avoid this we can use copy method

In [102]:

slice_of_arr

array([100, 100, 100, 100, 100])

In [103]:

arrs

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [106]:
arrs_copy = arrs.copy()

In [107]:
arrs_copy

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [108]:
arrs_copy[:] = 999

In [109]:
arrs_copy

array([999, 999, 999, 999, 999, 999, 999, 999, 999, 999])

In [110]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

Indexing and Selection of 2D Numpy Arrays

In [112]:
arr_2d = np.array([[10,15,20],[25,30,35],[40,45,50]])

In [113]:
arr_2d

array([[10, 15, 20],
       [25, 30, 35],
       [40, 45, 50]])

2 methods to grab elements froma 2D array. Single brackt and Double bracket

In [114]:
# Double bracket notation to grab 15

arr_2d[0][1]

15

In [115]:
arr_2d[2][1]

45

In [116]:
# Single bracket simply replaces brackets with commas

arr_2d[1,2]

35

In [118]:
arr_2d[1:,1:]

array([[30, 35],
       [45, 50]])

Conditional Selection

In [120]:
carr = np.arange(0,10)

In [121]:
carr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [123]:
# An operator on the array produces a boolean array

bool_carr=carr > 5

In [124]:
bool_carr

array([False, False, False, False, False, False,  True,  True,  True,  True], dtype=bool)

In [125]:
# We can use this boolean array to do selection by wrapping this in the original array

carr[bool_carr]

array([6, 7, 8, 9])

In [126]:
# This can be done in a single step

carr[carr>5]

array([6, 7, 8, 9])

In [127]:
ex_arr = np.arange(50).reshape(5,10)

In [128]:
ex_arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [129]:
ex_arr[3:,7:9]

array([[37, 38],
       [47, 48]])

NUMPY OPERATIONS

We can do operations of arrays with arrays or scalar operations

In [134]:
arr_op = np.arange(0,11)

In [135]:
arr_op + arr_op

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [136]:
arr_op - arr_op

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [137]:
# Here the 1st element is 0 and 0/0 is giving a nan value

arr_op/ arr_op

C:\Users\Sravani\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([ nan,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.])

In [139]:
# When 1 is divided by 0 we can get an infinte value

1/arr_op

C:\Users\Sravani\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([        inf,  1.        ,  0.5       ,  0.33333333,  0.25      ,
        0.2       ,  0.16666667,  0.14285714,  0.125     ,  0.11111111,
        0.1       ])

Universal Array Functions

In [140]:
arr_op.max()

10

In [141]:
np.max(arr_op)

10

In [145]:
np.sqrt(arr_op)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

NUMPY EXERCISE

In [148]:
# Create an array of 10 zeros
import numpy as np
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [149]:
# Create an array of 10 ones
import numpy as np
np.ones(10)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [168]:
# Create an array of 10 fives
import numpy as np
np.ones(10) * 5

array([ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.])

In [154]:
# Create an array of integers from 10 to 50

sample_arr = np.arange(10,51)

In [155]:
sample_arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [157]:
# Create an array of integers from 10 to 50

sample_arr[sample_arr%2==0]

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [159]:
# Create a 3X3 matrix from 0 to 8

np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [160]:
# Create a 3X3 identity matrix

np.eye(3,3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [161]:
# Random number b/w 0 to 1

np.random.rand()

0.7296430095712942

In [162]:
# To generate 25 random no's from standard normal distribution

np.random.randn(25)

array([ 1.02514933, -1.4581228 , -0.29819484, -0.85668907,  0.56817483,
        0.44834276,  2.32982778, -0.55423153, -0.63932438,  1.01569859,
        2.04904263, -1.38332706,  0.34094852,  0.11439422, -0.40564316,
        0.54080513,  1.0155721 ,  1.04453127, -0.38356139,  0.56688074,
        0.13438258, -0.06827187,  0.02537719, -0.80456603,  0.27552114])

In [172]:
np.arange(1,101).reshape(10,10)/100

array([[ 0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,  0.09,  0.1 ],
       [ 0.11,  0.12,  0.13,  0.14,  0.15,  0.16,  0.17,  0.18,  0.19,  0.2 ],
       [ 0.21,  0.22,  0.23,  0.24,  0.25,  0.26,  0.27,  0.28,  0.29,  0.3 ],
       [ 0.31,  0.32,  0.33,  0.34,  0.35,  0.36,  0.37,  0.38,  0.39,  0.4 ],
       [ 0.41,  0.42,  0.43,  0.44,  0.45,  0.46,  0.47,  0.48,  0.49,  0.5 ],
       [ 0.51,  0.52,  0.53,  0.54,  0.55,  0.56,  0.57,  0.58,  0.59,  0.6 ],
       [ 0.61,  0.62,  0.63,  0.64,  0.65,  0.66,  0.67,  0.68,  0.69,  0.7 ],
       [ 0.71,  0.72,  0.73,  0.74,  0.75,  0.76,  0.77,  0.78,  0.79,  0.8 ],
       [ 0.81,  0.82,  0.83,  0.84,  0.85,  0.86,  0.87,  0.88,  0.89,  0.9 ],
       [ 0.91,  0.92,  0.93,  0.94,  0.95,  0.96,  0.97,  0.98,  0.99,  1.  ]])

In [167]:
# Array of 20 linearly spaced elements from 0 to 1

np.linspace(0,1,20)

array([ 0.        ,  0.05263158,  0.10526316,  0.15789474,  0.21052632,
        0.26315789,  0.31578947,  0.36842105,  0.42105263,  0.47368421,
        0.52631579,  0.57894737,  0.63157895,  0.68421053,  0.73684211,
        0.78947368,  0.84210526,  0.89473684,  0.94736842,  1.        ])